---

- hosts: all
  become: yes
  become_method: sudo

  vars:
   - localzone: Europe/London

  tasks:

############################## Set Timezone ##############################

# Configure time zone
  - name: Set timezone variables for Debian / Ubuntu
    copy: content='{{ localzone }}'
          dest=/etc/timezone
          owner=root
          group=root
          mode=0644
          backup=yes
    notify:
      - update timezone
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - block:

    - name: Set timezone for CentOS / RHEL / Fedora
      file: src=/usr/share/zoneinfo/{{ localzone }}  dest=/etc/localtime state=link force=yes

    when: ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'

  handlers:

    - name: update timezone
      command: dpkg-reconfigure --frontend noninteractive tzdata
