---

- hosts: all
  become: yes
  become_method: sudo

  tasks:

############################## Fedora yum error fix ##############################

  - block:

    - name: Install yum for Fedora
      command: dnf install yum -y -q

    - name: Install Python
      yum: name=python state=latest update_cache=yes

    when: (ansible_distribution == "Fedora")

############################## Perl dependency ##############################

  - block:

    - name: Install perl minimal for CentOS 6.x / Oracle Linux 6.x
      yum: name=perl state=latest update_cache=yes

    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6") or (ansible_distribution == "OracleLinux" and ansible_distribution_major_version == "6") or (ansible_distribution == "Fedora")

############################## Perl Time/HiRes dependency ##############################

  - block:

    - name: Install perl-Time-HiRes for CentOS 6.x / OracleLinux 6.x
      yum: name=perl-Time-HiRes state=latest

    when: (ansible_distribution == "CentOS" or ansible_distribution == "OracleLinux") and (ansible_distribution_major_version == "6")

############################## nmon dev dependencies for Oracle Linux / CentOS ##############################

  - block:

    - name: Oracle Linux / CentOS - gcc dev dependencies for nmon compilation
      yum: name=gcc* state=latest

    when: (ansible_distribution == "OracleLinux" or ansible_distribution == "CentOS")

  - block:

    - name: Oracle Linux / CentOS - ncurses dev dependencies for nmon compilation
      yum: name=ncurses-dev* state=latest

    when: (ansible_distribution == "OracleLinux" or ansible_distribution == "CentOS")

  - block:

    - name: Oracle Linux / CentOS - make dev dependencies for nmon compilation
      yum: name=make state=latest

    when: (ansible_distribution == "OracleLinux" or ansible_distribution == "CentOS")

############################## nmon dev dependencies for Ubuntu / Debian ##############################

  - block:

    - name: Ubuntu / Debian - build-essentials
      apt: name=build-essential state=latest update_cache=yes

    when: (ansible_distribution == "Ubuntu" or ansible_distribution == "Debian")

  - block:

    - name: Ubuntu / Debian - ncurses dev dependencies for nmon compilation
      apt: name=libncurses5-dev state=latest
      ignore_errors: yes

    when: (ansible_distribution == "Ubuntu" or ansible_distribution == "Debian")

############################## nmon compilation ##############################

  - name: Copy nmon source code
    copy: src=/opt/nmon-binaries/lmon.c dest=/home/vagrant owner=vagrant group=vagrant
    when: (ansible_system == "Linux")

  - name: Copy makefile
    copy: src=/opt/nmon-binaries/makefile dest=/home/vagrant owner=vagrant group=vagrant
    when: (ansible_system == "Linux")

############################## Oracle Linux ##############################

  - command: "make nmon_x86_64_ol73"
    when: (ansible_distribution == "OracleLinux" and ansible_architecture == "x86_64" and ansible_distribution_version.startswith('7.3'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_64_ol72"
    when: (ansible_distribution == "OracleLinux" and ansible_architecture == "x86_64" and ansible_distribution_version.startswith('7.2'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_64_ol71"
    when: (ansible_distribution == "OracleLinux" and ansible_architecture == "x86_64" and ansible_distribution_version.startswith('7.1'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_64_ol70"
    when: (ansible_distribution == "OracleLinux" and ansible_architecture == "x86_64" and ansible_distribution_version.startswith('7.0'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_64_ol67"
    when: (ansible_distribution == "OracleLinux" and ansible_architecture == "x86_64" and ansible_distribution_version.startswith('6.7'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_64_ol66"
    when: (ansible_distribution == "OracleLinux" and ansible_architecture == "x86_64" and ansible_distribution_version.startswith('6.6'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_64_ol65"
    when: (ansible_distribution == "OracleLinux" and ansible_architecture == "x86_64" and ansible_distribution_version.startswith('6.5'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_64_ol64"
    when: (ansible_distribution == "OracleLinux" and ansible_architecture == "x86_64" and ansible_distribution_version.startswith('6.4'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_ol67"
    when: (ansible_distribution == "OracleLinux" and ansible_architecture == "i386" and ansible_distribution_version.startswith('6.7'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_ol66"
    when: (ansible_distribution == "OracleLinux" and ansible_architecture == "i386" and ansible_distribution_version.startswith('6.6'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_ol65"
    when: (ansible_distribution == "OracleLinux" and ansible_architecture == "i386" and ansible_distribution_version.startswith('6.5'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_ol64"
    when: (ansible_distribution == "OracleLinux" and ansible_architecture == "i386" and ansible_distribution_version.startswith('6.4'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

############################## nmon compilation ##############################

  - command: "make nmon_x86_64_centos73"
    when: (ansible_distribution == "CentOS" and ansible_architecture == "x86_64" and ansible_distribution_version.startswith('7.3'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_64_centos72"
    when: (ansible_distribution == "CentOS" and ansible_architecture == "x86_64" and ansible_distribution_version.startswith('7.2'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_64_centos71"
    when: (ansible_distribution == "CentOS" and ansible_architecture == "x86_64" and ansible_distribution_version.startswith('7.1'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_64_centos70"
    when: (ansible_distribution == "CentOS" and ansible_architecture == "x86_64" and ansible_distribution_version.startswith('7.0'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_64_centos68"
    when: (ansible_distribution == "CentOS" and ansible_architecture == "x86_64" and ansible_distribution_version.startswith('6.8'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_64_centos67"
    when: (ansible_distribution == "CentOS" and ansible_architecture == "x86_64" and ansible_distribution_version.startswith('6.7'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_64_centos66"
    when: (ansible_distribution == "CentOS" and ansible_architecture == "x86_64" and ansible_distribution_version.startswith('6.6'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_64_centos65"
    when: (ansible_distribution == "CentOS" and ansible_architecture == "x86_64" and ansible_distribution_version.startswith('6.5'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_64_centos64"
    when: (ansible_distribution == "CentOS" and ansible_architecture == "x86_64" and ansible_distribution_version.startswith('6.4'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_centos68"
    when: (ansible_distribution == "CentOS" and ansible_architecture == "i386" and ansible_distribution_version.startswith('6.8'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_centos67"
    when: (ansible_distribution == "CentOS" and ansible_architecture == "i386" and ansible_distribution_version.startswith('6.7'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_centos66"
    when: (ansible_distribution == "CentOS" and ansible_architecture == "i386" and ansible_distribution_version.startswith('6.6'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_centos65"
    when: (ansible_distribution == "CentOS" and ansible_architecture == "i386" and ansible_distribution_version.startswith('6.5'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_centos64"
    when: (ansible_distribution == "CentOS" and ansible_architecture == "i386" and ansible_distribution_version.startswith('6.4'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

############################## nmon compilation ##############################

  - command: "make nmon_x86_64_ubuntu1204"
    when: (ansible_distribution == "Ubuntu" and ansible_architecture == "x86_64" and ansible_distribution_version.startswith('12.04'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_64_ubuntu1404"
    when: (ansible_distribution == "Ubuntu" and ansible_architecture == "x86_64" and ansible_distribution_version.startswith('14.04'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_64_ubuntu1510"
    when: (ansible_distribution == "Ubuntu" and ansible_architecture == "x86_64" and ansible_distribution_version.startswith('15.10'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_64_ubuntu1604"
    when: (ansible_distribution == "Ubuntu" and ansible_architecture == "x86_64" and ansible_distribution_version.startswith('16.04'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_64_ubuntu1610"
    when: (ansible_distribution == "Ubuntu" and ansible_architecture == "x86_64" and ansible_distribution_version.startswith('16.10'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_64_ubuntu1704"
    when: (ansible_distribution == "Ubuntu" and ansible_architecture == "x86_64" and ansible_distribution_version.startswith('17.04'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_ubuntu1204"
    when: (ansible_distribution == "Ubuntu" and ansible_architecture == "i386" and ansible_distribution_version.startswith('12.04'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_ubuntu1404"
    when: (ansible_distribution == "Ubuntu" and ansible_architecture == "i386" and ansible_distribution_version.startswith('14.04'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_ubuntu1604"
    when: (ansible_distribution == "Ubuntu" and ansible_architecture == "i386" and ansible_distribution_version.startswith('16.04'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_ubuntu1610"
    when: (ansible_distribution == "Ubuntu" and ansible_architecture == "i386" and ansible_distribution_version.startswith('16.10'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_ubuntu1704"
    when: (ansible_distribution == "Ubuntu" and ansible_architecture == "i386" and ansible_distribution_version.startswith('17.04'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

############################## nmon compilation ##############################

  - command: "make nmon_x86_64_debian8"
    when: (ansible_distribution == "Debian" and ansible_architecture == "x86_64" and ansible_distribution_version.startswith('8'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_64_debian7"
    when: (ansible_distribution == "Debian" and ansible_architecture == "x86_64" and ansible_distribution_version.startswith('7'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_debian8"
    when: (ansible_distribution == "Debian" and ansible_architecture == "i386" and ansible_distribution_version.startswith('8'))
    become: yes
    become_user: vagrant
    ignore_errors: yes

  - command: "make nmon_x86_debian7"
    when: (ansible_distribution == "Debian" and ansible_architecture == "i386" and ansible_distribution_version.startswith('7'))
    become: yes
    become_user: vagrant
    ignore_errors: yes


  # Copy compiled binary
  - shell: "cp /home/vagrant/nmon* /opt/nmon-binaries/"
    when: (ansible_system == "Linux")
    become: yes
    become_user: vagrant
    ignore_errors: yes
